name: Build Android APK

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.2

      - name: Install Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'ndk;22.1.7171670 platforms;android-30 build-tools;30.0.3'

      - name: Set Android Environment Variables
        run: |
          echo "ANDROID_SDK=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/22.1.7171670" >> $GITHUB_ENV
          echo "$ANDROID_HOME/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Install Haxe Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.1.2
          haxelib install openfl 9.3.3
          haxelib install flixel 5.6.1
          haxelib install flixel-addons 3.2.2
          haxelib install flixel-ui
          haxelib install tjson 1.4.0
          haxelib install hscript
          haxelib install hxdiscord_rpc 1.2.4
          haxeplib install flxanimate
          haxeplib install extension-androidtools
          haxelib run lime setup -y
          haxeplib run lime setup android -y

      - name: Clean Broken Manifest
        run: |
          rm -f export/release/android/bin/app/src/main/AndroidManifest.xml
          rm -f export/debug/android/bin/app/src/main/AndroidManifest.xml

      - name: Compile Android APK
        run: haxelib run lime build android -D HXCPP_NO_PCH -D NO_PCH -release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            export/release/android/bin/app/build/outputs/apk/**/*.apk
            export/debug/android/bin/app/build/outputs/apk/**/*.apk
            
