name: Build Android APK

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'ndk;21.4.7075529 platforms;android-33 build-tools;33.0.2'

      - name: Set Android Environment Variables
        run: |
          echo "ANDROID_SDK=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Install Haxe Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.2.2
          haxelib install openfl 9.3.3
          haxelib install flixel 5.6.1
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hxargs
          haxelib install tjson
          haxelib install hscript
          haxelib install hxdiscord_rpc 1.2.4
          haxelib install flxanimate
          haxelib install extension-androidtools
          haxelib run lime setup -y
          haxelib run lime setup android -y

      - name: Compile Android APK
        run: haxelib run lime build android -release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          
